#!/bin/bash

if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

rm /var/www/html/*
cp ${PWD}/html/* /var/www/html/

rm /usr/lib/cgi-bin/*
cp ${PWD}/cgi/* /usr/lib/cgi-bin/
chmod 755 /usr/lib/cgi-bin/*

echo "Copied"
